In [2]:
from tensorflow.keras.preprocessing.text import one_hot

### Sentences

In [6]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

## Define the vocabulary size

In [7]:
voc_size=10000

### One Hot Representation

In [8]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[1390, 4315, 1644, 5041],
 [1390, 4315, 1644, 7294],
 [1390, 9086, 1644, 2180],
 [3047, 6868, 9689, 1109, 6360],
 [3047, 6868, 9689, 1109, 5898],
 [6843, 1390, 3781, 1644, 7293],
 [1962, 3804, 1201, 1109]]

## Word Embedding Representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences #we need to make the sentences with the same size
from tensorflow.keras.models import Sequential
import numpy as np

In [12]:
sent_lenght=8 #complete with 0 till we get len of 8
embedded_doc=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_lenght)#'pre' add the zeros on the beggining. 'post' is reverse
embedded_doc

array([[   0,    0,    0,    0, 1390, 4315, 1644, 5041],
       [   0,    0,    0,    0, 1390, 4315, 1644, 7294],
       [   0,    0,    0,    0, 1390, 9086, 1644, 2180],
       [   0,    0,    0, 3047, 6868, 9689, 1109, 6360],
       [   0,    0,    0, 3047, 6868, 9689, 1109, 5898],
       [   0,    0,    0, 6843, 1390, 3781, 1644, 7293],
       [   0,    0,    0,    0, 1962, 3804, 1201, 1109]])

## Feature representation

In [13]:
dim=10 #google word2vec has 300

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_lenght))#we don't train anything. Embedding layer is internaly using word2vec
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_doc)

1/1 [==============================] - 0s 268ms/step


array([[[-2.72455942e-02,  3.18298452e-02,  3.80720831e-02,
         -9.60644335e-03,  6.06024265e-03, -1.19729042e-02,
         -2.85681728e-02,  3.10239531e-02, -3.19283493e-02,
         -4.10046801e-02],
        [-2.72455942e-02,  3.18298452e-02,  3.80720831e-02,
         -9.60644335e-03,  6.06024265e-03, -1.19729042e-02,
         -2.85681728e-02,  3.10239531e-02, -3.19283493e-02,
         -4.10046801e-02],
        [-2.72455942e-02,  3.18298452e-02,  3.80720831e-02,
         -9.60644335e-03,  6.06024265e-03, -1.19729042e-02,
         -2.85681728e-02,  3.10239531e-02, -3.19283493e-02,
         -4.10046801e-02],
        [-2.72455942e-02,  3.18298452e-02,  3.80720831e-02,
         -9.60644335e-03,  6.06024265e-03, -1.19729042e-02,
         -2.85681728e-02,  3.10239531e-02, -3.19283493e-02,
         -4.10046801e-02],
        [ 1.14407912e-02,  6.69084862e-03, -9.13878530e-03,
         -2.77825724e-02,  2.11202241e-02, -2.44299322e-03,
         -1.71836242e-02, -1.00065358e-02,  8.899770

In [17]:
embedded_doc[0]

array([   0,    0,    0,    0, 1390, 4315, 1644, 5041])